name: Create tag

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  tagger:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        env:
          EVENT: ${{ toJSON(github.event) }}
        run: echo "$EVENT"

      - name: Create tag
        uses: actions/github-script@v3
        if: github.event.pull_request.merged && startsWith(github.event.pull_request.head.ref, 'release-')
        with:
          github-token: ${{ github.token }}
          script: |
            const tag = context.payload.pull_request.head.ref.replace("release-", "")
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/" + tag,
              sha: context.payload.pull_request.merge_commit_sha
            })

